apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  namespace: openshift-ingress-operator
  name: system 
spec:
  domain: system.redcluster.danila.home 
  endpointPublishingStrategy:
    type: LoadBalancerService
    loadBalancer:
      scope: Internal 